# This is where the TLS cert of LND is located
cert_path="<PATH>/.configs/playground/lnd-secrets/tls.cert"
# This is where the macaroon cert of LND is located
macaroon_path="<PATH>/.configs/playground/lnd-secrets/admin.macaroon"
# Where the lnd server is running
address="https://localhost:10009"
# Where LNDK is going to store its own TLS certificates
data_dir = "<PATH>/.configs/playground/lndk-data/"
log_level="trace"
