services:
  bitcoind:
    image: bitcoin/bitcoin:28.1
    platform: linux/arm64
    restart: unless-stopped
    networks:
      playground-net:
        ipv4_address: 172.30.1.1
    entrypoint: ["/bin/sh", "/bitcoin/entrypoint.sh"]
    volumes:
      - "bitcoind:/bitcoin"
      - "./conf/bitcoind/bitcoin.conf:/bitcoin/bitcoin.conf"
      - "./conf/bitcoind/entrypoint.sh:/bitcoin/entrypoint.sh"
    ports:
      - "18443:18443"

  lnd1:
    image: lightninglabs/lnd:v0.18.5-beta
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      playground-net:
        ipv4_address: 172.30.1.2
    command: --externalip=172.30.1.2 --externalip=lnd1:9735 --tlsextradomain=lnd1 --alias=lnd1 --color=#89CFF0
    volumes:
      - "lnd1:/root/.lnd"
      - "./conf/lnd/lnd.conf:/root/.lnd/lnd.conf"
    ports:
      - "10009:10009"
      - "8080:8080"

  eclair1:
    image: ampch/eclair:latest
    platform: linux/arm64
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      playground-net:
        ipv4_address: 172.30.1.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/eclair/logback-custom.xml
    volumes:
      - "eclair1:/data"
      - "./conf/eclair/eclair.conf:/data/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/data/logback-custom.xml"
    ports:
      - "9700:9700"
    healthcheck:
      test: ["CMD", "eclair-cli", "-p", "pass", "getinfo"]
      interval: 5s
      timeout: 10s
      retries: 5

  eclair2:
    image: ampch/eclair:latest
    platform: linux/arm64
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      playground-net:
        ipv4_address: 172.30.2.31
    environment:
      - JAVA_OPTS=-Declair.printToConsole -Dakka.loglevel=DEBUG -Dlogback.configurationFile=/eclair/logback-custom.xml
    volumes:
      - "eclair2:/data"
      - "./conf/eclair/eclair2.conf:/data/eclair.conf"
      - "./conf/eclair/logback-custom.xml:/data/logback-custom.xml"
    ports:
      - "9800:9800"
    healthcheck:
      test: ["CMD", "eclair-cli", "-p", "pass", "getinfo"]
      interval: 5s
      timeout: 10s
      retries: 5

  cln1:
    image: elementsproject/lightningd:latest
    restart: unless-stopped
    depends_on:
      - bitcoind
    networks:
      playground-net:
        ipv4_address: 172.30.1.30
    entrypoint: ["/cln_wait_for.sh"]
    command: --network=regtest --addr=0.0.0.0:9735 --announce-addr=172.30.1.30:9735 --bitcoin-retry-timeout=180 --developer --dev-fast-gossip --dev-bitcoind-poll=2 --alias=cln1 --rgb=FF0000
    volumes:
      - "cln1:/root/.lightning"
      - "bitcoind:/root/.lightning/bitcoin:ro"
      - "./conf/cln/config:/root/.lightning/config"
      - "./scripts/cln_wait_for.sh:/cln_wait_for.sh"
    healthcheck:
      test: ["CMD", "lightning-cli", "getinfo"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  bitcoind:
  lnd1:
  eclair1:
  eclair2:
  cln1:

networks:
  playground-net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
